[package]
name = "userspace"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
chrono = "0.4.39"
jsonwebtoken = "9.3.0"
lettre = "0.11.11"
mongodb = "3.2.0"
rocket = "0.5.1"
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
validator = "0.20.0"
