[package]
name = "userspace"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = "2.2.6"
dotenv = "0.15.0"
jsonwebtoken = "9.3.0"
lettre = "0.11.11"
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0.217", features = ["derive"] }
sqlx = "0.8.3"
tokio = { version = "1.43.0", features = ["full"] }
uuid = "1.12.1"
validator = "0.20.0"
