name: Deploy Userspace

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/blank/userspace
    steps:
      - name: Pull latest changes
        run: git pull origin main
      
      - name: Run migrations
        run: cargo sqlx migrate run
        working-directory: /home/blank/userspace/RUST-API/userspace

      - name: Build Application
        run: cargo build --release
        working-directory: /home/blank/userspace/RUST-API/userspace

      - name: Restart userspace Service
        run: sudo systemctl restart userspace

      - name: Check status
        run: sudo systemctl status userspace