name: Deploy Userspace

on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/blank/userspace
    steps:
      - name: Pull latest changes
        run: git pull origin main
      
      - name: Run database migrations
        run: cargo sqlx migrate run
        working-directory: /home/blank/userspace/RUST-API/userspace

  build:
    needs: prepare
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/blank/userspace/RUST-API/userspace
    steps:
      - name: Build Application
        run: cargo build --release

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Restart userspace Service
        run: sudo systemctl restart userspace
      
      - name: Verify Deployment
        run: |
          sleep 10  # Give service time to start
          sudo systemctl status userspace
          if [ $? -ne 0 ]; then
            echo "Service failed to start properly"
            exit 1
          fi